# Generated by Django 4.1.7 on 2023-03-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicmodelling', '0002_alter_image_image_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
